//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery_Sanin_Cheprasov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string FirsName { get; set; }
        public string LastName { get; set; }
        public string Patronumic { get; set; }
        public int PostID { get; set; }
        public int GenderCode { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<int> IDUser { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual PostStaff PostStaff { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
